name: Generate xxjssyou README

on:
  workflow_dispatch:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]
  push:
    branches:
      - main
    paths:
      - main.py

jobs:
  sync:
    name: Generate README
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'push' ||
      (github.event.issue && github.repository_owner_id == github.event.issue.user.id) ||
      (github.event.comment && github.repository_owner_id == github.event.comment.user.id)
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          source venv/bin/activate
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt found, installing default dependencies"
            pip install requests python-dotenv
          fi

      - name: Generate new md
        run: |
          source venv/bin/activate
          if [ -n "${{ github.event.issue.number }}" ]; then
            python main.py ${{ secrets.G_T }} ${{ github.repository }} --issue_number '${{ github.event.issue.number }}'
          else
            python main.py ${{ secrets.G_T }} ${{ github.repository }}
          fi

      - name: Check for changes
        id: changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add BACKUP/*.md
          # 检查是否有变化
          if git diff --staged --quiet; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "No changes to commit"
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "Changes detected, will commit and push"
          fi

      - name: Commit and Push
        if: steps.changes.outputs.has_changes == 'true'
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "update new blog"
          branch: main
