name: Process GitHub Issues

on:
  workflow_dispatch:

jobs:
  process-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install axios

      - name: Process GitHub Issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          # 创建 Node.js 脚本来处理 API 请求
          cat > process_issues.js << 'EOF'
          const axios = require('axios');

          const token = process.env.GITHUB_TOKEN;
          const repo = process.env.REPO;

          async function getIssues() {
            try {
              const response = await axios.get(
                `https://api.github.com/repos/${repo}/issues?state=open`,
                {
                  headers: {
                    Authorization: `token ${token}`,
                    Accept: 'application/vnd.github.v3+json'
                  }
                }
              );

              response.data.forEach(issue => {
                console.log(`- [#${issue.number}](${issue.html_url}) ${issue.title}`);
              });
            } catch (error) {
              console.error('Error fetching issues:', error.message);
              process.exit(1);
            }
          }

          getIssues();
          EOF

          node process_issues.js
