  name: Update README with issues using curl and jq
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    REPO: ${{ github.repository }}
  run: |
    # 安装 jq (JSON 处理器)
    sudo apt-get update && sudo apt-get install -y jq
    
    # 获取 issues 并更新 README
    issues=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
      "https://api.github.com/repos/$REPO/issues?state=open" | \
      jq -r '.[] | select(.pull_request == null) | "- [#\(.number)](\(.html_url)) \(.title)"')
    
    if [ -z "$issues" ]; then
      issues="No open issues at the moment."
    fi
    
    # 更新 README.md
    awk -v issues="$issues" '
      /<!-- ISSUES-START -->/ { print; print issues; skip=1 }
      /<!-- ISSUES-END -->/ { skip=0 }
      !skip { print }
      skip && /<!-- ISSUES-END -->/ { print; skip=0 }
    ' README.md > README.tmp && mv README.tmp README.md
    
    echo "README updated successfully"
